-- liquibase formatted sql
-- changeset liquibase:1
CREATE TABLE IF NOT EXISTS public.study_progress_dict (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(255),
    CONSTRAINT "study_progress_dict_pk" PRIMARY KEY (id)
);

-- changeset liquibase:2
INSERT INTO public.study_progress_dict (id, text) VALUES (2, 'неуд');
INSERT INTO public.study_progress_dict (id, text) VALUES (3, 'уд');
INSERT INTO public.study_progress_dict (id, text) VALUES (4, 'хор');
INSERT INTO public.study_progress_dict (id, text) VALUES (5, 'отл');
