-- liquibase formatted sql
-- changeset liquibase:1
CREATE TABLE IF NOT EXISTS public.student_list (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name varchar(255),
    birth_date date,
    progress_id INTEGER,        
    CONSTRAINT "student_list_pk" PRIMARY KEY (id)
);
ALTER TABLE public.student_list ADD CONSTRAINT student_list_fk FOREIGN KEY (progress_id) REFERENCES study_progress_dict(id);